import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "@/hooks/LayoutWrapper";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Afrochow",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>{/* Include metadata, styles, etc. */}</head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
         
            
           
                <LayoutWrapper>{children}</LayoutWrapper>
           
         
         
      </body>
    </html>
  );
}
